# Generated by Django 3.1.6 on 2021-02-05 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveServicioConTopeCFDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveProducto', models.IntegerField()),
                ('tope', models.FloatField()),
                ('keyName', models.CharField(blank=True, max_length=32, null=True)),
                ('keyValue', models.CharField(blank=True, max_length=32, null=True)),
                ('isPatial', models.CharField(default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteCFDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256)),
                ('fileName', models.CharField(max_length=256)),
                ('metodoPago', models.CharField(blank=True, max_length=3, null=True)),
                ('tipoComprobante', models.CharField(max_length=1)),
                ('total', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('moneda', models.CharField(max_length=3)),
                ('certificado', models.CharField(max_length=256)),
                ('fecha', models.DateField()),
                ('emisorRFC', models.CharField(max_length=20)),
                ('emisorName', models.CharField(max_length=200)),
                ('emisorRegimen', models.CharField(max_length=3)),
                ('receptorRFC', models.CharField(max_length=20)),
                ('receptorName', models.CharField(max_length=200)),
                ('condiciones', models.CharField(blank=True, max_length=512, null=True)),
                ('totalImpuestosRet', models.FloatField(blank=True, default=0.0, null=True)),
                ('totalImpuestosTras', models.FloatField(blank=True, default=0.0, null=True)),
                ('totalDeducible', models.FloatField(blank=True, default=0.0, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoCDFI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveProducto', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=3)),
                ('des', models.CharField(max_length=200)),
                ('valorUnitario', models.FloatField()),
                ('importe', models.FloatField()),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comprobantecfdi')),
            ],
        ),
        migrations.CreateModel(
            name='DescargaCFDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSolicitud', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('num_cfdis', models.IntegerField()),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('rfc_solicitante', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsoCFDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3)),
                ('des', models.CharField(max_length=200)),
                ('isPartial', models.CharField(default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Satuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fielKey', models.CharField(max_length=200)),
                ('fielCer', models.CharField(max_length=200)),
                ('fielPas', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaquete', models.CharField(max_length=200)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.descargacfdi')),
            ],
        ),
        migrations.CreateModel(
            name='ImpuestosConceptoCFDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idImpuesto', models.CharField(max_length=3)),
                ('idTipo', models.CharField(blank=True, max_length=3, null=True)),
                ('tipoFactor', models.CharField(blank=True, max_length=8, null=True)),
                ('tasaOCuota', models.FloatField(blank=True, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conceptocdfi')),
            ],
        ),
        migrations.CreateModel(
            name='ImpuestosCDFI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idImpuesto', models.CharField(max_length=3)),
                ('idTipo', models.CharField(max_length=3)),
                ('tipoFactor', models.CharField(blank=True, max_length=8, null=True)),
                ('tasaOCuota', models.FloatField(blank=True, null=True)),
                ('importe', models.FloatField()),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comprobantecfdi')),
            ],
        ),
        migrations.AddField(
            model_name='comprobantecfdi',
            name='uso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usocfdi'),
        ),
        migrations.CreateModel(
            name='ComplementoConceptoCDFI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyName', models.CharField(blank=True, max_length=32, null=True)),
                ('keyValue', models.CharField(blank=True, max_length=32, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conceptocdfi')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comprobantecfdi',
            constraint=models.UniqueConstraint(fields=('uuid', 'tipoComprobante'), name='unique_comprobante'),
        ),
    ]
