# Generated by Django 4.0.3 on 2022-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecfdi',
            name='tipoCambio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
