# Generated by Django 4.0.3 on 2022-04-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comprobantecfdi_tipocambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecfdi',
            name='tipoCambio',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
