# Generated by Django 4.0.3 on 2023-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comprobantecfdi_tipocambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecfdi',
            name='tipoCambio',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
