# Generated by Django 4.0.3 on 2023-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comprobantecfdi_tipocambio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosEfecturados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('impuesto', models.CharField(max_length=3)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TablasDeISR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('limiteInferior', models.FloatField()),
                ('limiteSuperior', models.FloatField()),
                ('cuotaFija', models.FloatField()),
                ('porcentajeExcedente', models.FloatField()),
            ],
        ),
    ]
