# Generated by Django 4.0.3 on 2023-05-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tablasdeisr_limitesuperior'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosefecturados',
            name='tipo',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
