# Generated by Django 4.0.3 on 2023-05-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pagosefecturados_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuestoscdfi',
            name='importeDeducible',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
