# Generated by Django 4.0.3 on 2023-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_impuestoscdfi_importededucible'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecfdi',
            name='totalImpuestosTrasDeducible',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
