# Generated by Django 4.2.1 on 2023-06-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comprobantecfdi_totalimpuestostrasdeducible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('period', models.CharField(max_length=64)),
                ('fecha', models.DateField()),
                ('operationNumber', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('media', models.CharField(max_length=64)),
                ('isrInFavor', models.FloatField(blank=True, default=0.0, null=True)),
                ('isrInCharge', models.FloatField(blank=True, default=0.0, null=True)),
                ('isrToBePay', models.FloatField(blank=True, default=0.0, null=True)),
                ('ivaInFavor', models.FloatField(blank=True, default=0.0, null=True)),
                ('ivaInCharge', models.FloatField(blank=True, default=0.0, null=True)),
                ('ivaToBePay', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pagosefecturados',
            name='references',
            field=models.ManyToManyField(to='app.declaracion'),
        ),
    ]
